version: "3"
services:
  postgres:
    container_name: postgres
    image: postgres:13.3-alpine
    restart: always
    env_file:
      - ./.env.dev
    ports:
      - ${PG_PORT}:${PG_PORT}
    volumes:
      - "postgres_data:/bitnami/postgres/data"
    environment:
      - POSTGRES_DB=${PG_NAME}
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_PASSWORD=${PG_PASS}
  postgres-adminer:
    container_name: postgres-adminer
    image: adminer
    restart: always
    ports:
      - 8080:8080
volumes:
  postgres_data:
    external: true
